// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDSW_1.Data;

#nullable disable

namespace ProyectoDSW_1.Migrations
{
    [DbContext(typeof(APPDbContext))]
    [Migration("20260422031954_CambioTieneDueno")]
    partial class CambioTieneDueno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoDSW_1.Models.Deuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFacturacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimitePago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoDeuda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TiendaId");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Dueno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Duenos");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeudaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeudaId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DuenoId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneDueno")
                        .HasColumnType("bit");

                    b.Property<bool>("alquiler")
                        .HasColumnType("bit");

                    b.Property<double>("costoAlquiler")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DuenoId");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("contraseñaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Deuda", b =>
                {
                    b.HasOne("ProyectoDSW_1.Models.Servicio", "Servicios")
                        .WithMany("Deudas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDSW_1.Models.Tienda", "Tienda")
                        .WithMany("Deudas")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicios");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Dueno", b =>
                {
                    b.HasOne("ProyectoDSW_1.Models.Usuario", "Usuario")
                        .WithOne("Dueno")
                        .HasForeignKey("ProyectoDSW_1.Models.Dueno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Pago", b =>
                {
                    b.HasOne("ProyectoDSW_1.Models.Deuda", "deudas")
                        .WithOne("Pago")
                        .HasForeignKey("ProyectoDSW_1.Models.Pago", "DeudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deudas");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Tienda", b =>
                {
                    b.HasOne("ProyectoDSW_1.Models.Dueno", "Dueno")
                        .WithMany("Tiendas")
                        .HasForeignKey("DuenoId");

                    b.Navigation("Dueno");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoDSW_1.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Deuda", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Dueno", b =>
                {
                    b.Navigation("Tiendas");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Servicio", b =>
                {
                    b.Navigation("Deudas");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Tienda", b =>
                {
                    b.Navigation("Deudas");
                });

            modelBuilder.Entity("ProyectoDSW_1.Models.Usuario", b =>
                {
                    b.Navigation("Dueno");
                });
#pragma warning restore 612, 618
        }
    }
}
